name: API Automation Tests with Postman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Node.js (Newman yêu cầu Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Bước 3: Cài đặt Newman
      - name: Install Newman
        run: npm install -g newman
      - name: Install Newman Report
        run: npm install -g newman-reporter-htmlextra

      # Bước 4: Chạy Postman collection
      - name: Run Postman collection
        run: newman run ./tests/api_collection.json 
        #run: newman run ./tests/api_collection.json -r htmlextra --reporter-htmlextra-export ./reports/report.html
        #run: newman run ./tests/api_collection.json -e ./tests/environment.json

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: reports/
