name: API Automation Tests with Postman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Node.js (Newman yêu cầu Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Bước 3: Cài đặt Newman
      - name: Install Newman and reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create reports directory
        run: mkdir -p reports

      # Bước 4: Chạy Postman collection
      - name: Run Postman collection
        #run: newman run ./tests/api_collection.json 
        run: newman run ./tests/api_collection.json -r htmlextra --reporter-htmlextra-export ./reports/report.html
        #run: newman run ./tests/api_collection.json -e ./tests/environment.json

      - name: Upload report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./reports
           destination_dir: reports
           keep_files: false # Xóa các file cũ trong nhánh gh-pages trước khi đẩy mới
        if: always()

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/report.html #https://trangvt.github.io/API-Test-Automation/reports/report.html
        if: always()
